services:
  frontend-prod:
    image: ghcr.io/chandu-sasidharan/bbb-frontend:prod
    container_name: bbb-frontend-prod
    expose:
      - '3000'
    networks:
      - edge_net
    restart: unless-stopped

  backend-prod:
    image: ghcr.io/chandu-sasidharan/bbb-backend:prod
    container_name: bbb-backend-prod
    expose:
      - '4000'
    env_file:
      - ./backend/.env.prod
    networks:
      - edge_net
    restart: unless-stopped

networks:
  edge_net:
    external: true
