services:
  frontend-staging:
    image: ghcr.io/chandu-sasidharan/bio-baum-bauer-frontend:staging
    expose:
      - '3000'
    networks:
      - edge_net
    restart: unless-stopped

  backend-staging:
    image: ghcr.io/chandu-sasidharan/bio-baum-bauer-backend:staging
    expose:
      - '4000'
    env_file:
      - ./backend/.env.stage
    networks:
      - edge_net
    restart: unless-stopped

networks:
  edge_net:
    external: true
