version: '3.8'

services:
  frontend:
    image: ghcr.io/chandu-sasidharan/bio-baum-bauer-frontend:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - ./frontend/.env.prod
    restart: unless-stopped

  backend:
    image: ghcr.io/chandu-sasidharan/bio-baum-bauer-backend:latest
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env.prod
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
