services:
  frontend-stage:
    image: ghcr.io/chandu-sasidharan/bbb-frontend:stage
    container_name: bbb-frontend-stage
    expose:
      - '3000'
    networks:
      - edge_net
    restart: unless-stopped

  backend-stage:
    image: ghcr.io/chandu-sasidharan/bbb-backend:stage
    container_name: bbb-backend-stage
    expose:
      - '4000'
    env_file:
      - ./backend/.env.stage
    networks:
      - edge_net
    restart: unless-stopped

networks:
  edge_net:
    external: true
